// Single source of truth for hub content.
// /bedrock/ reads public/data/bedrock/*.json, generated by scripts/gen_bedrock.py (daily cron).

export const profile = {
  name: 'Sean',
  role: 'Cloud Infrastructure Architect',
  org: 'AWS Professional Services, Korea',
  tagline:
    'AWS 위에서 네트워크·랜딩존·AI 워크로드 플랫폼을 설계하고, 불편한 건 직접 만들어 씁니다.',
  location: 'Seoul, KR',
  email: 'seanson2709@gmail.com',
  links: {
    linkedin: 'https://www.linkedin.com/in/seungwoo-son-a7145a19a/',
    github: 'https://github.com/Sean2709',
    velog: 'https://velog.io/@seanson2709',
    rss: 'https://v2.velog.io/rss/@seanson2709',
  },
};

export type Cert = {
  name: string;
  short: string;
  level: 'Professional' | 'Specialty' | 'Associate' | 'Foundational' | 'Other';
  issuer: 'AWS' | 'CNCF' | 'Cisco';
  earned: string; // YYYY-MM
  expires?: string; // YYYY-MM
};

export const certs: Cert[] = [
  { name: 'AWS Certified Generative AI Developer – Professional', short: 'GenAI Dev Pro', level: 'Professional', issuer: 'AWS', earned: '2026-09', expires: '2029-09' },
  { name: 'AWS Certified Solutions Architect – Professional', short: 'SA Pro', level: 'Professional', issuer: 'AWS', earned: '2020-08', expires: '2029-05' },
  { name: 'AWS Certified Advanced Networking – Specialty', short: 'ANS', level: 'Specialty', issuer: 'AWS', earned: '2026-08', expires: '2029-08' },
  { name: 'AWS Certified AI Practitioner', short: 'AIF', level: 'Foundational', issuer: 'AWS', earned: '2026-07', expires: '2029-09' },
  { name: 'AWS Certified Solutions Architect – Associate', short: 'SAA', level: 'Associate', issuer: 'AWS', earned: '2020-07' },
  { name: 'AWS Certified Cloud Practitioner', short: 'CLF', level: 'Foundational', issuer: 'AWS', earned: '2020-06' },
  { name: 'Certified Kubernetes Administrator', short: 'CKA', level: 'Other', issuer: 'CNCF', earned: '2022-10' },
  { name: 'Certified Kubernetes Application Developer', short: 'CKAD', level: 'Other', issuer: 'CNCF', earned: '2022-11' },
];

export type App = {
  name: string;
  subtitle: string;
  desc: string;
  category: string;
  url: string;
  version: string;
  released: string; // YYYY-MM-DD
  icon: string; // /img/apps/*.png (160px, from the app's AppIcon 1024)
};

export const apps: App[] = [
  {
    name: '너그거알아',
    subtitle: '매일 하나, 상식 퀴즈',
    desc: '매일 자정 도착하는 4지선다 상식 한 문제. 스트릭·위젯, 계정·서버 없이 기기 안에만 저장. iOS.',
    category: 'Education',
    url: 'https://apps.apple.com/kr/app/id6814826377',
    version: '1.0',
    released: '2026-09-24',
    icon: '/img/apps/knowthat.png',
  },
  {
    name: '작심: 습관 리그',
    subtitle: '매일 루틴 체크, 목표 달성 트래커',
    desc: '습관을 리그로 겨루는 iOS 습관 트래커. SwiftUI + 서버 정산.',
    category: 'Productivity',
    url: 'https://apps.apple.com/kr/app/id6804211842',
    version: '1.1.0',
    released: '2026-08-26',
    icon: '/img/apps/jaksim.png',
  },
  {
    name: '은퇴하면 만수르',
    subtitle: '내 은퇴 자산 시뮬레이터',
    desc: '물가를 반영한 연금·자산 시뮬레이션과 순위 카드. iOS.',
    category: 'Finance',
    url: 'https://apps.apple.com/kr/app/id6801016602',
    version: '1.0',
    released: '2026-08-17',
    icon: '/img/apps/mansur.png',
  },
];

export type Post = {
  title: string;
  url: string;
  date: string; // YYYY-MM-DD
  tags: string[];
};

export const posts: Post[] = [
  {
    title: '쉽게 따라하는 LZA를 활용한 AWS Control Tower 구축 (2) - OU / 계정 / SCP를 코드로 관리하기',
    url: 'https://velog.io/@seanson2709/%EC%89%BD%EA%B2%8C-%EB%94%B0%EB%9D%BC%ED%95%98%EB%8A%94-LZA%EB%A5%BC-%ED%99%9C%EC%9A%A9%ED%95%9C-AWS-Control-Tower-%EA%B5%AC%EC%B6%95-2-OU-%EA%B3%84%EC%A0%95-SCP%EB%A5%BC-%EC%BD%94%EB%93%9C%EB%A1%9C-%EA%B4%80%EB%A6%AC%ED%95%98%EA%B8%B0',
    date: '2026-09-24',
    tags: ['aws', 'lza', 'control-tower', 'organizations', 'scp'],
  },
  {
    title: '쉽게 따라하는 Amazon Bedrock으로 나만의 AI 어시스턴트 만들기 (2) — iPhone 앱 붙이기: SwiftUI + SSE',
    url: 'https://velog.io/@seanson2709/%EC%89%BD%EA%B2%8C-%EB%94%B0%EB%9D%BC%ED%95%98%EB%8A%94-Amazon-Bedrock%EC%9C%BC%EB%A1%9C-%EB%82%98%EB%A7%8C%EC%9D%98-AI-%EC%96%B4%EC%8B%9C%EC%8A%A4%ED%84%B4%ED%8A%B8-%EB%A7%8C%EB%93%A4%EA%B8%B0-2-iPhone-%EC%95%B1-%EB%B6%99%EC%9D%B4%EA%B8%B0-SwiftUI-SSE',
    date: '2026-09-22',
    tags: ['aws', 'bedrock', 'ios', 'swiftui', 'sse'],
  },
  {
    title: '쉽게 따라하는 Amazon Bedrock으로 나만의 AI 어시스턴트 만들기 (1) — 첫 호출부터 대화·도구 호출까지',
    url: 'https://velog.io/@seanson2709/%EC%89%BD%EA%B2%8C-%EB%94%B0%EB%9D%BC%ED%95%98%EB%8A%94-Amazon-Bedrock%EC%9C%BC%EB%A1%9C-%EB%82%98%EB%A7%8C%EC%9D%98-AI-%EC%96%B4%EC%8B%9C%EC%8A%A4%ED%84%B4%ED%8A%B8-%EB%A7%8C%EB%93%A4%EA%B8%B0-1-%EC%B2%AB-%ED%98%B8%EC%B6%9C%EB%B6%80%ED%84%B0-%EB%8C%80%ED%99%94%EB%8F%84%EA%B5%AC-%ED%98%B8%EC%B6%9C%EA%B9%8C%EC%A7%80',
    date: '2026-09-20',
    tags: ['aws', 'bedrock', 'python', 'boto3'],
  },
  {
    title: '쉽게 따라하는 LZA를 활용한 AWS Control Tower 구축 - Stack / CodePipeline 배포',
    url: 'https://velog.io/@seanson2709/%EC%89%BD%EA%B2%8C-%EB%94%B0%EB%9D%BC%ED%95%98%EB%8A%94-LZA%EB%A5%BC-%ED%99%9C%EC%9A%A9%ED%95%9C-AWS-Control-Tower-%EA%B5%AC%EC%B6%95',
    date: '2025-06-30',
    tags: ['aws', 'lza', 'control-tower', 'landing-zone'],
  },
];

export const focus = [
  'AWS 네트워크 · 랜딩존 (Transit Gateway, Network Firewall, LZA / Control Tower)',
  'Amazon Bedrock 기반 AI 워크로드 플랫폼 · 거버넌스 · FinOps',
  'Kubernetes / 플랫폼 엔지니어링 (CKA · CKAD)',
];

// Analytics beacon (cookie-less, self-hosted). The site key is a public anti-junk
// token: API Gateway rejects POSTs without it (or without our Origin) before any
// Lambda runs. Reading stats needs a separate admin bearer token that never ships.
// Infra: infra/analytics/ (API GW HTTP API → Lambda → DynamoDB, ap-northeast-2).
export const analytics = {
  endpoint: 'https://zoviv9w83h.execute-api.ap-northeast-2.amazonaws.com',
  siteKey: 'f6df7409e1891e4b8153c7a1',
};

// /admin/ sign-in: Google Identity Services. The OAuth *client ID* is public by design
// (it ships in every GIS page); access is decided server-side by the Lambda authorizer,
// which verifies the Google ID token and checks the e-mail against ADMIN_EMAILS.
export const admin = {
  googleClientId: '53886632583-rg6ckd1ph9chkniojam8kc065ems88hp.apps.googleusercontent.com',
  email: 'seanson2709@gmail.com',
};
